Repository kubernetes/sig-security, pull requests merged in 2022-04, with the labels that each got.

#47 Learning sessions added
  sig-security-tooling/learning-sessions.md
Labels: approved, lgtm, sig/security, tide/merge-method-squash, size/S, cncf-cla: yes

#46 Rename subdir for the current audit
  sig-security-external-audit/security-audit-2021-2022/RFP.md
  sig-security-external-audit/security-audit-2021-2022/RFP_Decision.md
Labels: size/XS, approved, lgtm, cncf-cla: yes

#45 Add learning session request GitHub Issue template
  .github/ISSUE_TEMPLATE/request-learning-session.md
Labels: size/M, approved, lgtm, sig/security, cncf-cla: yes
